name    'puppetlabs-keystone'
version '2.2.0'
source  'https://github.com/stackforge/puppet-keystone'
author  'Puppet Labs'
license 'Apache License 2.0'
summary 'Puppet Labs Keystone Module'
description 'Puppet module to install and configure the Openstack identity service'
project_page 'https://launchpad.net/puppet-openstack'

dependency 'puppetlabs/nginx', '> 0'
dependency 'puppetlabs/apache', '> 0'
dependency 'puppetlabs/inifile', '> 0'
dependency 'puppetlabs/mysql', '>= 2'
dependency 'puppetlabs/stdlib', '>= 2.5.0'
